ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include ../../../prodroot_pkt.mk

EXTRA_INCVPATH+= $(IOPKT_ROOT)/sys $(IOPKT_ROOT)/sys/sys-nto $(IOPKT_ROOT)/lib/socket/public

LIBS = drvrS cacheS

NAME = devnp-$(PROJECT)

USEFILE=$(PROJECT_ROOT)/$(NAME).use

define PINFO
PINFO DESCRIPTION=Driver for Intel 82544 Gigabit Ethernet controllers
endef



#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

